// <auto-generated />
namespace DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_nullable_variables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_nullable_variables));
        
        string IMigrationMetadata.Id
        {
            get { return "201907042310096_test_nullable_variables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
